### ISSUE TITLE
Any way to get the fusion file?

### ISSUE THREAD

**Issue by CurzonEden** [tachoknight/xyz-zero-finder#4]
Perhaps I'm doing something wrong but I wanted to CAM this out on fusion. However when I download and open the mesh on fusion it scales the size to 14" x 14" which seems very large in comparison to the youtube link.

So sorry if this is something simple that I've just missed

**Comment by tachoknight** [comment]
Sure thing, sorry I didn't respond earlier as I was traveling. Try this link: [Fusion 360 ShopBot Edge Finder](https://a360.co/2HCUOws)
